server:
  port: 10010

spring:
  application:
    name: couponKing-merchant-admin
  datasource:
#    url: jdbc:mysql://localhost:3306/coupon_king_rebuild?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.200.72:3306/coupon_king_rebuild?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: abc123
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: localhost
#      host: 192.168.200.72
      port: 6379
#      password: abc123


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaoshuai66.couponking

knife4j:
  enable: true
  setting:
    language: zh_cn

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: couponKing_merchant-admin-service_common-message-execute_pg
    send-message-timeout: 2000 # 发送超时时间
    retry-times-when-send-failed: 1 # 同步发送重试次数
    retry-times-when-send-async-failed: 1 # 异步发送重试次数
