version: '3'

services:
  redis:
    image: redis:7.0.4
    container_name: coupon-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/etc/redis/conf
    command: redis-server /etc/redis/conf/redis.conf
    restart: always
  mysql:
    image: mysql:5.7.36
    container_name: coupon-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123'
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
      - mysql-conf:/etc/mysql/conf.d
    restart: always
volumes:
  mysql-data:
  mysql-logs:
  mysql-conf:
  redis-data:
  redis-conf:


